### ISSUE TITLE
Please add a LICENSE file

### ISSUE THREAD

**Issue by mithro** [stefanpie/sa-placer#1]
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

Thanks!

**Comment by stefanpie** [comment]
Added an initial license: "GNU Affero General Public License v3.0"

Can change in the future; this is one we have used in my research lab for past open source research projects.

**Comment by mithro** [comment]
You are of course welcome to use any license you want but I would recommend a permissive license (like Apache 2.0 / BSD / MIT) to allow future integration with other open source FPGA tools like VtR.
